### ISSUE TITLE
TinyCsvParser 3.0 Features

### ISSUE THREAD

**Issue by bytefish** [TinyCsvParser/TinyCsvParser#58]
I have started several rewrites of TinyCsvParser 3.0, but I am not happy with the rewrites. 

Here is my unordered TODO list for a 3.0:

- [ ] Support Asynchronous Parsing
- [ ] Support ``IAsyncEnumerable`` for Cancellation of Parsing
- [ ] Drop PLINQ Support
- [ ] Improve Error Handling, because at the moment it is hard to debug Parsing errors
- [ ] Rewrite the RFC4180 Parser for better handling of Quoted Newlines
- [ ] Rewrite the RFC4180 Parser to use more memory efficient ``ReadOnlySpan``
- [ ] Support ``System.Range`` in the API for mapping ranges
- [ ] Support Mapping based on Header Names
- [ ] Rework the Mapping API for more detailed error messages

Feel free to comment and add your ideas.

**Comment by ayberkcanturk** [comment]
Please can you add support for .NET dynamic, ExpandoObject support based on header names of the csv?

**Comment by bytefish** [comment]
For now I have no intentions to update to 3.0.
