### ISSUE TITLE
Document how to write custom converters

### ISSUE THREAD

**Issue by Andrioden** [TinyCsvParser/TinyCsvParser#61]
I struggled to find out how to write a custom converter/filter for the mapping. The only reason i figured it out was because i googled it and found this [page](https://bytefish.de/blog/timeseries_databases_1_dataset/) with custom converters as part of the examples.

The documentation contains examples of how to **use** custom converters, but not how to **write** them. My suggestion is to add a tutorial page about [here](https://bytefish.github.io/TinyCsvParser/sections/tutorials/custom_formats.html#).

Here is one silly example, which i actually ended up using to allow the parsing to fail parsing the headers, so I could read the headers from the `CsvMappingResult.Error.UnmappedRow`.

``` c#
public CsvSomethingMapping() : base()
{
	MapProperty(0, x => x.SomeValue, new NoSpaceAllowedConverter());
}
```

``` c#
public class NoSpaceAllowedConverter : ITypeConverter<string>
{
	public bool TryConvert(string value, out string result)
	{
		if (value.Contains(" "))
		{
			result = null;
			return false;
		}
		else
		{
			result = value;
			return true;
		}
	}

	public Type TargetType
	{
		get { return typeof(string); }
	}
}
```

Cheers! = )

**Comment by bytefish** [comment]
Thanks for your valuable feedback. 😎 It sounds great. 

I will add an example the days ahead!

**Comment by bytefish** [comment]
The documentation will be reworked with a 3.0 release. I am closing this for now.
