### ISSUE TITLE
Query on how to use generics 

### ISSUE THREAD

**Issue by rajaramanwork** [TinyCsvParser/TinyCsvParser#65]
public IList<T> ParseCSVFile<T>(string fileName)
        {
            var recordsList = new List<T>();
            CsvParserOptions csvParserOptions = new CsvParserOptions(true, ',');
            **var csvMapper = new CsvPreTradeMapping();**
            _CsvParser<T> csvParser = new CsvParser<T>(csvParserOptions, csvMapper);_
            var records = csvParser
                .ReadFromFile(fileName, Encoding.ASCII)
                .ToList();
            foreach (var item in records)
                recordsList.Add(item.Result);
            return recordsList;
        }

How do I convert this to  a generic type 
var csvMapper = new CsvPreTradeMapping();

The one in italic doesnt compile.

**Comment by bytefish** [comment]
@rajaramanwork Sorry for the huge delay. You have resolved it yourself by now, so I am closing it.
