### ISSUE TITLE
support for string with BOMs

### ISSUE THREAD

**Issue by herme063** [TinyCsvParser/TinyCsvParser#72]
Can we add support for stripping byte order markers from strings?

I am trying to parse the same string from files with different encoding (UTF8 vs UTF8-BOM) and the header is coming up with additional characters. I tried to create a separate parser instance just for the header, but the "extra" character is still prepended to the first column header value. 

Thank you,

**Comment by bytefish** [comment]
Can you add to sample files to this issue?
