### ISSUE TITLE
How to map 3 strings into one object?

### ISSUE THREAD

**Issue by Mage111** [TinyCsvParser/TinyCsvParser#74]
I have an object with 10 strings and one object "Error" that contains 3 strigs.
how can I do the mapping?

**Comment by bytefish** [comment]
I would simplify it a bit. I would have two classes, a flat one that maps to the FAV column and a model class, that has the Error Object for three properties. When reading the data you can do a mapping between both by using a ``Select`` operator on the stream.

**Comment by Mage111** [comment]
can you please give me an example of how can I use the 'select' operator in the mapping?
thanks!

**Comment by bytefish** [comment]
Sure. 

So the idea is to first have a class, that is basically a 1 to 1 mapping to your CSV file, no nested properties:

```csharp
    /// <summary>
    /// Simple class, no nested objects.
    /// </summary>
    class CsvData
    {
        public string ID { get; set; }

        public string Name { get; set; }

        public string ErrorCode { get; set; }

        public string ErrorMessage { get; set; }
    }
```

Next you have your real model with your data and a nested error class:

```csharp
    /// <summary>
    /// Your Error Model.
    /// </summary>
    class Error
    {
        public string Code { get; set; }

        public string Message { get; set; }
    }

    /// <summary>
    /// Your Data.
    /// </summary>
    class Data
    {
        public string ID { get; set; }

        public string Name { get; set; }

        public Error Error { get; set; }
    }
```

Now you do your mapping, I don't know your data here is an example:

```csharp
    private class CsvDataMapping : CsvMapping<CsvData>
    {
        public CsvDataMapping ()
            : base()
        {
            MapProperty(0, x => x.ID);
            MapProperty(1, x => x.Name);
            MapProperty(2, x => x.ErrorCode);
            MapProperty(3, x => x.Message);
        }
    }
```

And finally you construct your parser and read the data. Using the ``Select`` Operator you convert from your flat ``CsvData`` class to the complex ``Data`` class, which contains the nested ``Error``:

```
        CsvParserOptions csvParserOptions = new CsvParserOptions(true, ';');
        CsvDataMapping csvMapper = new CsvDataMapping();
        CsvParser<CsvData> csvParser = new CsvParser<CsvData>(csvParserOptions, csvMapper);

        var result = csvParser
            .ReadFromFile(@"your_data.csv", Encoding.ASCII)
            .Where(csvData => csvData.IsValid)
            .Select(csvData => new Data
            {
                ID = csvData.ID,
                Name = csvData.Name,
                Error = new Error
                {
                    Code = csvData.ErrorCode,
                    Message = csvData.ErrorMessage
                }
            })
            .ToList();

```

So this doesn't require you to map nested properties. You can learn more about LINQ here:

* https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/concepts/linq/

**Comment by Mage111** [comment]
Hi,

thanks for your quick response.

meanwhile, I solved it in another way, by using `MapUsing`

the object is as your example, and the mapping is:
     ```
            MapProperty(0, x => x.ID);
            MapProperty(1, x => x.Name);
            MapUsing((entity, values) =>
            {               
                var error = new Error (values.Tokens[2], values.Tokens[3]);
                entity.Error =error;
                return true;
            });`
```
from my side, the issue can be closed
