### ISSUE TITLE
Converting empty string to decimal

### ISSUE THREAD

**Issue by schuttea** [TinyCsvParser/TinyCsvParser#75]
Hello is it possible to convert empty values to a decimal of 0.
Right know i get a lot of:
with Value '' cannot be converted: csvline.

Regards,

A. Schutte

**Comment by bytefish** [comment]
Use a Nullable in your Class, like ``decimal?``.

**Comment by schuttea** [comment]
thx i thought i did it already but it did the trick.
I needed the value to be converted to 0.
  var valids = Records.Where(e => e.IsValid).Select(s => { s.Result.Type = type; s.Result.MyDecimalProperty??= 0;  return s.Result; } );
