### ISSUE TITLE
Parsing CSV with varied columns

### ISSUE THREAD

**Issue by rohit3d2003** [TinyCsvParser/TinyCsvParser#76]
I have a situation where I am parsing CSV’s with varying column schema e.g first file has 10 elements and second 15. I have defined a common Mapper but when a column is missing, it throws an exception. Any idea how to handle it? There is no way for me to know upfront about the number and sequence of elements

**Comment by PotatoTroll** [comment]
Same issue here, the last columns are optional in my case, so there is no fixed column number.

**Comment by bytefish** [comment]
What would an API look like for the given use cases? I mean, if you had a wish, then what would be the most intuitive way to define the record structure described?

**Comment by bytefish** [comment]
I am closing, as I cannot imagine what the API can look like. Please give me some ideas how you want to define the mappings.
