### ISSUE TITLE
Parser throws an exception if there are several quotes within a string-column

### ISSUE THREAD

**Issue by ckrahlisch** [TinyCsvParser/TinyCsvParser#78]
TinyCsvParser throws an exception if there are several quotes within a string-column. Is there a way to just ignore it or to parse the string correctly? For example from separator to the next separator.

It's about the following line:
```c#
.AppendLine("\"Michael, Chester\",\"Also goes by \" \", among friends that is\",24")
```
What i expected ```Also goes by " " among friends that is```
But the parser only recognizes ```Also goes by``` for the description-property and the processing of the following column leads to an exception.

```CSVMappingError - "Column 2 with Value ' among friends that is' cannot be converted"```

The parser tries to use the rest of the string for the following mapping.
In this case for the age property.

Here is the complete code if you want to test it yourself:

```c#
private class SampleEntity
{
    public string Name { get; set; }
    public string Description { get; set; }
    public int Age { get; set; }
}

private class SampleEntityMapping : CsvMapping<SampleEntity>
{
    public SampleEntityMapping()
    {
        MapProperty(0, x => x.Name);
        MapProperty(1, x => x.Description);
        MapProperty(2, x => x.Age);
    }
}

[Fact]
public void RFC4180_CsvParser_Integration_Test()
{
    // Use a " as Quote Character, a \\ as Escape Character and a , as Delimiter.
    var options = new Options('"', '\\', ',');

    // Initialize the Rfc4180 Tokenizer:
    var tokenizer = new RFC4180Tokenizer(options);

    // Now Build the Parser:
    var csvParserOptions = new CsvParserOptions(true, tokenizer);
    var csvMapper = new SampleEntityMapping();
    var csvParser = new CsvParser<SampleEntity>(csvParserOptions, csvMapper);

    var stringBuilder = new StringBuilder()
        .AppendLine("Name, Age, Description")
        .AppendLine("\"Michael, Chester\",\"Also goes by \" \" among friends that is\",24")
        .AppendLine("\"Robert, Willliamson\",\"All-around nice guy who always says hi\",17");

    // Define the NewLine Character to split at:
    var csvReaderOptions = new CsvReaderOptions(new[] {Environment.NewLine});

    var result = csvParser
        .ReadFromString(csvReaderOptions, stringBuilder.ToString())
        .ToList();

    Assert.Equal("Also goes by \" \", among friends that is", result[0].Result.Description);
}
```
Is there a way to work around this? If not it would be nice if you fix it. Sometimes csv-files are not as clean as we would like them to be.

Thank you, nice project.

**Comment by bytefish** [comment]
The PR has been merged so this ticket should have been resolved for @ckrahlisch. 

If it's still an open issue, please reopen.
