### ISSUE TITLE
MapUsing not available in version 2.6.1

### ISSUE THREAD

**Issue by KaizerT** [TinyCsvParser/TinyCsvParser#81]
We upgraded from 2.5.2 to 2.6.1 and realized that the mapusing function we were trying to use in the documentation was not avaiable.

The documentation only calls out 2.6.0 so not sure if someone made a breaking change the newest version.

documentation we were referring to
https://tinycsvparser.github.io/TinyCsvParser/sections/tutorials/custom_mapping.html#example

**Comment by bytefish** [comment]
I cannot see something has been removed between 2.6.0 and 2.6.1:

* https://github.com/TinyCsvParser/TinyCsvParser/compare/2.5.2...2.6.1

Could you please check, what AssemblyVersion is acutally used in the bin/ Folder of your project?

**Comment by KaizerT** [comment]
Hello, apologies on how long it took me to reply. yeah the assembly version was at 2.6.1 when we were testing. we got it off of nuget. not sure if the error compiling the nupkg. 

I did retry again to upgrade the service we were using to 2.6.1 and it works now. Not sure what happened there.
