### ISSUE TITLE
Vulnerability in System.Text.RegularExpressions

### ISSUE THREAD

**Issue by JoaoSeverino** [TinyCsvParser/TinyCsvParser#86]
Currently, TinyCsvParser uses NuGet System.Text.RegularExpressions version 4.3.0 which has a known vulnerability and should be upgraded to a patched version.

See https://github.com/advisories/GHSA-cmhx-cq75-c4mj

**Comment by bytefish** [comment]
I will update the dependency and release it as a new 2.6.2. The other PR has some breaking changes I think, and it should be a 3.0. What do you think?

**Comment by JoaoSeverino** [comment]
That is perfectly OK

**Comment by JoaoSeverino** [comment]
I also now noticed another vulnerability in the Test and Benchmark projects for Microsoft.NETCore.App NuGet (see https://github.com/advisories/GHSA-7mfr-774f-w5r9)

But the original one is the only one that affects the product itself.

**Comment by bytefish** [comment]
I think disabling dependabot wasn’t that clever. 😇

**Comment by bytefish** [comment]
I removed the ``net45`` Target Framework, because it isn't supported anymore. Instead ``netstandard2.0``, ``netstandard2.1`` and ``net6.0`` are targeted. The latter is probably not required, because ``.net6.0`` should support ``netstandard2.1`` anyway.
