### ISSUE TITLE
CsvParserExtensions methods do not support ICsvParser<TEntity>

### ISSUE THREAD

**Issue by blueneosky** [TinyCsvParser/TinyCsvParser#87]
Hello,

As methods of CsvParserExtensions are not applied on ICsvParser<TEntity> but CsvParser<TEntity>, this is not full compatible with Dependency Injection.

Is there any limitation ?

**Comment by bytefish** [comment]
You are totally right. They should have been applied on the ``ICsvParser`` interface. I will fix this and release a 2.7.0. 

It’s also probably better to add these methods directly to the interface in the future. I recently had some issues with mocking Microsoft ``ILogger`` interfaces, which made me realize Extension methods are probably not _that cool_. 

What do you think?

**Comment by blueneosky** [comment]
Thank you for your reactivity.

For your question, the real question can be : is there any other implementation of this interface ?
If no, go ahead.
Otherwize, you can mutate the extension into helper. Each implementation of these new methods of the interface will be redirected to the helper. A boilerplate for each new implemetation.
Let me know if you don't understand me for the last part, it's late for me. Sorry.

**Comment by bytefish** [comment]
It's fixed in Version 2.7.0, which will be listed as soon as NuGet indexes it.

**Comment by bytefish** [comment]
I will make changes to the interface in Version 3.0 to simplify mocking and Dependency Injection.

**Comment by blueneosky** [comment]
Ok, nice
Think you for your reactivity !
