### ISSUE TITLE
Community namespace

### ISSUE THREAD

**Issue by Miista** [TinyCsvParser/TinyCsvParser#91]
Is there a specific sub-namespace to use for community packages?

**Comment by bytefish** [comment]
No, feel free to use `TinyCsvParser.YourExtension` as a package name! 😎

**Comment by Miista** [comment]
Great! I have published the following packages:

- TinyCsvParser.Optional (https://github.com/Miista/TinyCsvParser.Optional)
- TinyCsvParser.Collections (https://github.com/Miista/TinyCsvParser.Collections)
- TinyCsvParser.ImmutableCollections (https://github.com/Miista/TinyCsvParser.ImmutableCollections)

We can close this issue.

**Comment by bytefish** [comment]
Great! Let’s leave it open, until I have referenced them in the README!

**Comment by Miista** [comment]
@bytefish There was one more:

* TinyCsvParser.Enums (https://github.com/Miista/TinyCsvParser.Enums)

**Comment by bytefish** [comment]
@Miista Sorry, it took so long! 😓 I have added the Links to the README. Thanks for your great work! ✌️
