### ISSUE TITLE
Add support for .NET 8/9 

### ISSUE THREAD

**Issue by Externius** [TinyCsvParser/TinyCsvParser#97]
Hi,

The current targetframeworks has .net6 in it which has reached the end of support, so maybe it would be a good idea to remove that and add .net8/.net9 to it.
Also, the used nuget packages could be updated too.

**Comment by bytefish** [comment]
Good work! I have merged the Pull Request and I am going to release a new package tomorrow. 👍🏻

**Comment by bytefish** [comment]
Released!
